events {}

http {
  upstream fintech-prod  { server fintech-prod:8000; }
  upstream cyberdyne-ops { server cyberdyne-ops:8000; }

  map $http_x_tenant_id $backend {
    "fintech-prod"  fintech-prod;
    "cyberdyne-ops" cyberdyne-ops;
    default         fintech-prod;
  }

  server {
    listen 80;

    location / {
      proxy_pass         http://$backend;
      proxy_set_header   X-Tenant-ID $http_x_tenant_id;
      proxy_set_header   Host $host;
      proxy_set_header   X-Real-IP $remote_addr;
      proxy_connect_timeout 5s;
      proxy_read_timeout 10s;
    }
  }
}
